"""
Notation conventions used throughout the PCI library.

This module is *descriptive* — it documents the symbol conventions and provides
a few constants. The actual classes live elsewhere in the package.

Variables
---------
A : array of shape (n,)
    Treatment / exposure variable. Continuous in DGP1/DGP2, binary (or
    coarsened-binary) in DGP3.
Y : array of shape (n,)
    Outcome variable.
U : array of shape (n,) [latent]
    Unobserved confounder. Generated by the DGP but not passed to estimators
    (oracle methods get U as a sanity reference).
W : array of shape (n,) or (n, p_W)
    **Negative-control outcome** (NCO) — proxy of U that is conditionally
    independent of A given (U, X).  Convention follows Tchetgen Tchetgen et al.
    (2024). NB: Kallus / Bennett papers use the *opposite* convention.
Z : array of shape (n,) or (n, p_Z)
    **Negative-control exposure** (NCE) — proxy of U that is conditionally
    independent of Y given (U, A, X).
X : array of shape (n, p_X) or None
    Observable covariates that are conditioned on but NOT residualised.
    Empirical experience: residualising on X can collapse the proxy
    structure on real data.

Bridge functions
----------------
h : callable (W, A, X) -> R
    Outcome bridge satisfying  E[Y|A,Z,X] = E[h(W,A,X) | A,Z,X].
q : callable (Z, A, X) -> R
    Treatment bridge satisfying the dual moment restriction. In the policy
    formulation, q is the Riesz representer of the policy functional.

Estimands
---------
ATE  E[Y(1) - Y(0)]                       average treatment effect (binary A)
GACE J(pi) = E[Y(pi(A)) | do(...)]        generalised ACE for stochastic policy
                                          pi : R -> Delta(R)
J_dr_a   the doubly-robust estimator of the dose-response curve a -> J at dose a

Standard identification assumptions
-----------------------------------
A1  consistency
A2  positivity / overlap on (A | U, X)
A3  no interference (SUTVA)
A4  proxy independence W ⊥ A | (U, X)         — defines W as NCO
A5  proxy independence Z ⊥ Y | (A, U, X)      — defines Z as NCE
A6  completeness (existence + uniqueness of h, q solutions to Fredholm Eq.)

Common estimator-tuning symbols
-------------------------------
ell_h, ell_W, ell_A, ell_Z   length-scales for kernels in W / A / Z spaces
m_h          number of random Fourier features for the h-bridge (Bennett-RFF)
lambda_h     Tikhonov regularisation strength for h
lambda_r     Tikhonov regularisation strength for q (Riesz)
SNR          signal-to-noise ratio defining proxy quality:
             SNR_W = sigma_U^2 / (sigma_U^2 + sigma_W^2)   (idem for Z)

References
----------
Tchetgen Tchetgen E.J., Ying A., Cui Y., Shi X., Miao W. (2024).
    *An Introduction to Proximal Causal Inference*. Statistical Science 39(3).
Cui Y., Pu H., Shi X., Miao W., Tchetgen Tchetgen E.J. (2024).
    *Semiparametric Proximal Causal Inference*. JASA 119(546).
Bennett A. et al. (2023). *Source Condition Double Robust Inference on
    Functionals of Inverse Problems*. arXiv:2307.13793.
Mastouri A. et al. (2021). *Proximal Causal Learning with Kernels*. ICML.
"""
from __future__ import annotations


# Default reference SNR (good-regime baseline)
DEFAULT_SNR_REFERENCE = 0.95
DEFAULT_SIGMA_U = 1.0
