"""
pci/tests/test_runner.py
========================

Reproducibility tests for the canonical Monte Carlo runner utilities in
``pci.runner``. These ensure that the PKL caches under
``simulations/results/raw/`` (which back every figure in S6 and S7) can
be regenerated bit-identically at any time.
"""
from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pytest


# ════════════════════════════════════════════════════════════════════════════
#  bandwidth_helpers (C5.1)
# ════════════════════════════════════════════════════════════════════════════

def test_silverman_h_deterministic():
    """Silverman bandwidth is a pure function of the input array."""
    from pci.runner.bandwidth_helpers import _silverman_h
    rng = np.random.default_rng(7)
    A = rng.standard_normal(500)
    h1 = _silverman_h(A)
    h2 = _silverman_h(A)
    assert h1 == h2
    assert h1 > 0


def test_median_bandwidth_deterministic():
    from pci.runner.bandwidth_helpers import _median_bandwidth
    rng = np.random.default_rng(7)
    X = rng.standard_normal((300, 2))
    b1 = _median_bandwidth(X)
    b2 = _median_bandwidth(X)
    assert b1 == b2
    assert b1 > 0


def test_compute_J_policy_true_dgp2_shape():
    """_compute_J_policy_true returns a value per dose, finite, monotone-ish."""
    from pci.runner.bandwidth_helpers import _compute_J_policy_true, _silverman_h
    from pci.dgps.michaelis_menten import MichaelisMentenDGP
    dgp = MichaelisMentenDGP(snr_W=0.95, snr_Z=0.95)
    s = dgp.generate(n=2000, seed=1)
    h_KDE = _silverman_h(s.A)
    a_grid = np.array([1.8, 2.2, 2.6, 3.0])
    J_pt = _compute_J_policy_true(dgp, a_grid, h_KDE)
    assert J_pt.shape == (4,)
    assert np.all(np.isfinite(J_pt))


def test_bandwidth_helpers_shim_identity():
    """Original dgp2_bias_diagnostics.py re-exports must be the same Python objects."""
    from pci.runner.bandwidth_helpers import _silverman_h as A
    from simulations.experiments.dgp2_bias_diagnostics import _silverman_h as B
    assert A is B


# ════════════════════════════════════════════════════════════════════════════
#  block_runner (C5.2)
# ════════════════════════════════════════════════════════════════════════════

def test_block_runner_deterministic_smoke(tmp_path: Path):
    """_run_block produces bit-identical records for the same seed.

    This is the *cornerstone* of reproducibility: every PKL under
    simulations/results/raw/ is generated by _run_block.
    """
    from pci.runner.block_runner import _run_block
    from pci.dgps.michaelis_menten import MichaelisMentenDGP
    from pci.tuning.factories import make_bennett_estimator, BENNETT_DEFAULTS
    from pci.runner.bandwidth_helpers import _silverman_h, _median_bandwidth

    dgp = MichaelisMentenDGP(snr_W=0.95, snr_Z=0.95)
    ref = dgp.generate(n=500, seed=1)
    h_KDE = _silverman_h(ref.A)
    ell_W = _median_bandwidth(ref.W)
    ell_A = _median_bandwidth(ref.A)
    ell_Z = _median_bandwidth(ref.Z)
    a_grid = np.array([1.8, 2.2, 2.6, 3.0])
    J_pt = np.array([1.0, 1.1, 1.2, 1.3])

    config = dict(BENNETT_DEFAULTS)
    config.update({"m_h": 200, "m_c": 100, "n_features_r": 100})

    def factory():
        est = make_bennett_estimator(
            config, dgp, h_KDE, ell_W, ell_A, ell_Z,
            a_grid=a_grid.tolist(), ref_dose_index=2,
        )
        est.n_folds = 2
        return est

    out1_dir = tmp_path / "run1"
    out2_dir = tmp_path / "run2"
    data1 = _run_block(dgp, factory, a_grid, J_pt,
                        n=200, M=2, seed_base=12345,
                        label="smoke", raw_dir=out1_dir)
    data2 = _run_block(dgp, factory, a_grid, J_pt,
                        n=200, M=2, seed_base=12345,
                        label="smoke", raw_dir=out2_dir)
    assert len(data1["records"]) == len(data2["records"])
    n_finite = 0
    for r1, r2 in zip(data1["records"], data2["records"]):
        if r1.get("error") is None and r2.get("error") is None:
            j1 = np.asarray(r1.get("J_dr"))
            j2 = np.asarray(r2.get("J_dr"))
            np.testing.assert_allclose(j1, j2, rtol=1e-9,
                err_msg="block_runner non-deterministic for fixed seed_base")
            n_finite += 1
    assert n_finite > 0, "no successful records to check"


def test_block_runner_shim_identity():
    from pci.runner.block_runner import _run_block as A
    from simulations.experiments.dgp2_bias_diagnostics import _run_block as B
    assert A is B


# ════════════════════════════════════════════════════════════════════════════
#  diagnostics (C5.3) -- shim is intentionally a thin wrapper to preserve
#  the local REF_IDX (different scripts use different default ref_idx).
# ════════════════════════════════════════════════════════════════════════════

def test_decompose_callable():
    """_decompose is importable and callable; signature accepts ref_idx kwarg."""
    from pci.runner.diagnostics import _decompose
    import inspect
    assert callable(_decompose)
    sig = inspect.signature(_decompose)
    assert "ref_idx" in sig.parameters, (
        "_decompose must take ref_idx (different DGPs use different default)"
    )


def test_diagnostics_shim_is_wrapper():
    """The shim wraps the canonical _decompose to preserve the local REF_IDX
    semantics. Both must be callable; identity is NOT preserved here."""
    from pci.runner.diagnostics import _decompose as canonical
    from simulations.experiments.dgp2_bias_diagnostics import _decompose as wrapped
    assert callable(canonical)
    assert callable(wrapped)
