"""
Phase 16 -- Figure generation.

Generates 6 PNG figures for the S6 essay:
  F1 -- Conceptual diagram: bridge mismatch (3 functionals x 3 oracles)
  F2 -- DGP1 sanity heatmap (from existing Phase 15C E1 pkls, no new compute)
  F3 -- DGP2 coverage heatmap (from EXP-A)
  F4 -- bse vs dose curves (from EXP-A)
  F5 -- Proxy feasibility 4-panel heatmap (from EXP-B)
  F6 -- Spectral kappa vs bse scatter (from EXP-C)

All saved as PNG (200dpi) in essay/figures/phase16_F*.png.

Requires:
  - Phase 16 EXP-A, EXP-B, EXP-C completed
  - phase16_synthesis_data.json generated by _phase16_synthesis.py
"""
from __future__ import annotations

import json
import os
import pickle
from pathlib import Path
from typing import Dict

os.environ.setdefault("OPENBLAS_NUM_THREADS", "4")

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import ListedColormap

_BASE_DIR = Path(__file__).resolve().parents[2]
_FIGS_DIR = _BASE_DIR / "essay" / "figures"
_DATA_PATH = _BASE_DIR / "docs" / "notes" / "phase16_synthesis_data.json"
_E1_DIR = _BASE_DIR / "simulations" / "results" / "raw" / "simulation" / "dgp1_sanity"

A_GRID = np.array([1.8, 2.2, 2.6, 3.0])
REF_IDX = 2
METHOD_COLORS = {
    "linearDR":     "#D72638",   # red (matches phase19 METHOD_OVERRIDE)
    "KPVREG":       "#3F88C5",   # blue
    "DRKPV":        "#FFA500",   # orange
    "best_bennett": "#1A535C",   # dark teal
    "oracle":       "#000000",   # black
    "naiveREG":     "#888888",   # grey
    "linearREG":    "#FFB54C",   # light orange
    "best_kallus":  "#7B2CBF",   # purple
}
METHOD_LABELS = {
    "linearDR":     "linearDR",
    "KPVREG":       "KPVREG",
    "DRKPV":        "DRKPV",
    "best_bennett": "best_bennett",
    "oracle":       "oracle",
    "naiveREG":     "naiveREG",
    "linearREG":    "linearREG",
    "best_kallus":  "best_kallus",
}


def _load_data() -> dict:
    if not _DATA_PATH.exists():
        raise RuntimeError(
            f"phase16_synthesis_data.json not found at {_DATA_PATH}. "
            f"Run `python -m simulations.archive.utilities._phase16_synthesis` first."
        )
    return json.loads(_DATA_PATH.read_text(encoding="utf-8"))


def _parse_cell_key(key: str):
    """Parse 'n__snr' or 'snrW__snrZ' back to tuple."""
    parts = key.split("__")
    return (float(parts[0]), float(parts[1]))


# ══════════════════════════════════════════════════════════════════════════════
# F1 -- Conceptual: bridge mismatch
# ══════════════════════════════════════════════════════════════════════════════

def fig1_bridge_mismatch():
    fig, ax = plt.subplots(figsize=(11, 6.5))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 8)
    ax.axis("off")

    # 3 functional columns
    funcs = [
        ("m(a) = E[Y^a]", "Pointwise dose response", 1.5),
        ("J_GACE(a) = m(a)\nintegrated over policy", "Cui-style mean,\ndelta-policy = m(a)", 5.5),
        ("J(pi_{a,h})\n= integrated over\nGaussian policy", "What we ESTIMATE\n(continuous policy)", 9.5),
    ]
    for name, desc, x in funcs:
        rect = mpatches.FancyBboxPatch(
            (x - 1.5, 6), 3, 1.5,
            boxstyle="round,pad=0.1",
            edgecolor="black", facecolor="#E8F4F8", linewidth=1.5
        )
        ax.add_patch(rect)
        ax.text(x, 7.0, name, ha="center", va="center", fontsize=11, fontweight="bold")
        ax.text(x, 6.4, desc, ha="center", va="center", fontsize=8, style="italic")

    # Bridge equation row
    bridges = [
        ("h_0 satisfies\nE[Y - h_0 | Z, A] = 0\n(Fredholm eq.)", 1.5, "#FFE6E6"),
        ("h_0 same for all\nfunctionals (Cui Rmk 6)", 5.5, "#FFE6E6"),
        ("h_0 same eq. but\npolicy-dep. plug-in T_pi", 9.5, "#FFE6E6"),
    ]
    for txt, x, col in bridges:
        rect = mpatches.FancyBboxPatch(
            (x - 1.5, 4), 3, 1.4,
            boxstyle="round,pad=0.1",
            edgecolor="black", facecolor=col, linewidth=1
        )
        ax.add_patch(rect)
        ax.text(x, 4.7, txt, ha="center", va="center", fontsize=9)

    # Riesz / q row
    riesz = [
        ("q_0 = 1/f(A|U)\nGACE Riesz", 1.5, "#E6FFE6"),
        ("q_0 = 1/f(A|U)\nsame as m(a)", 5.5, "#E6FFE6"),
        ("r_pi = policy-specific\nRiesz; r_pi != q_0\n!! KEY POINT !!", 9.5, "#FFD6D6"),
    ]
    for txt, x, col in riesz:
        rect = mpatches.FancyBboxPatch(
            (x - 1.5, 2), 3, 1.4,
            boxstyle="round,pad=0.1",
            edgecolor="black", facecolor=col, linewidth=1.2
        )
        ax.add_patch(rect)
        ax.text(x, 2.7, txt, ha="center", va="center", fontsize=9)

    # Methods row
    methods = [
        ("DR/IPW for E[Y^a]\n(Cui 2023 EIF)", 1.5),
        ("DR/IPW for E[Y^a]\nintegrated", 5.5),
        ("Bennett: directly\ntargets J(pi)\nKPVREG: plug-in only", 9.5),
    ]
    for txt, x in methods:
        rect = mpatches.FancyBboxPatch(
            (x - 1.5, 0.2), 3, 1.2,
            boxstyle="round,pad=0.1",
            edgecolor="black", facecolor="#F0F0F0", linewidth=1
        )
        ax.add_patch(rect)
        ax.text(x, 0.8, txt, ha="center", va="center", fontsize=9)

    # Row labels
    ax.text(0.2, 6.7, "Functional", ha="left", va="center", fontsize=10, fontweight="bold", color="darkblue")
    ax.text(0.2, 4.7, "Bridge h", ha="left", va="center", fontsize=10, fontweight="bold", color="darkred")
    ax.text(0.2, 2.7, "Riesz r/q", ha="left", va="center", fontsize=10, fontweight="bold", color="darkgreen")
    ax.text(0.2, 0.8, "Estimator",   ha="left", va="center", fontsize=10, fontweight="bold")

    ax.set_title("Three functionals, three sets of bridges -- the 'oracle' label is ambiguous",
                  fontsize=12, fontweight="bold", pad=15)

    out = _FIGS_DIR / "phase16_F1_bridge_mismatch.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# F2 -- DGP1 sanity heatmap (from existing E1 pkls)
# ══════════════════════════════════════════════════════════════════════════════

def fig2_dgp1_sanity():
    methods_order = ["oracle", "linearREG", "linearDR", "KPVREG", "DRKPV",
                     "best_bennett", "best_kallus", "naiveREG"]
    n_list = [1000, 2000]
    metric_data = np.full((len(methods_order), len(n_list)), np.nan)
    cov_data = np.full((len(methods_order), len(n_list)), np.nan)

    for j, n in enumerate(n_list):
        cell_dir = _E1_DIR / f"n{n}"
        if not cell_dir.exists():
            continue
        for i, method in enumerate(methods_order):
            pkl = cell_dir / f"{method}_M100.pkl"
            if not pkl.exists():
                continue
            with open(pkl, "rb") as fh:
                data = pickle.load(fh)
            recs = [r for r in data["records"] if r.get("error") is None]
            if not recs:
                continue
            J_pt = np.array(data["meta"]["J_policy_true"])
            J_dr = np.array([r["J_dr"] for r in recs])
            V_hg = np.array([r["V_hat_grid"] for r in recs])
            with np.errstate(invalid="ignore"):
                se = np.sqrt(np.maximum(V_hg, 0.0) / n)
            ref = min(REF_IDX, J_pt.shape[0] - 1)
            bias = float(np.mean(J_dr[:, ref]) - J_pt[ref])
            se_m = float(np.nanmean(se[:, ref]))
            metric_data[i, j] = abs(bias) / se_m if se_m > 1e-15 else float("nan")
            cov_data[i, j] = float(np.mean(np.abs(J_dr[:, ref] - J_pt[ref]) <= 1.96 * se[:, ref]))

    fig, axes = plt.subplots(1, 2, figsize=(11, 5))

    for ax, data, title, vmin, vmax, cmap in [
        (axes[0], metric_data, "bse_ref (|bias|/SE)", 0, 2, "Reds"),
        (axes[1], cov_data, "Coverage (target=0.95)", 0.5, 1.0, "RdYlGn"),
    ]:
        im = ax.imshow(data, aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax)
        ax.set_xticks(range(len(n_list)))
        ax.set_xticklabels([f"n={n}" for n in n_list])
        ax.set_yticks(range(len(methods_order)))
        ax.set_yticklabels(methods_order)
        ax.set_title(f"DGP1 {title}", fontsize=11, fontweight="bold")
        for i in range(len(methods_order)):
            for j in range(len(n_list)):
                v = data[i, j]
                if np.isfinite(v):
                    ax.text(j, i, f"{v:.3f}", ha="center", va="center",
                            color="white" if (cmap == "Reds" and v > 1) or (cmap == "RdYlGn" and v < 0.7) else "black",
                            fontsize=9)
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    fig.tight_layout()

    out = _FIGS_DIR / "phase16_F2_dgp1_sanity.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# F3 -- DGP2 coverage heatmap (from EXP-A)
# ══════════════════════════════════════════════════════════════════════════════

def fig3_coverage_map(data: dict):
    cfg = data["config"]
    methods = cfg["METHODS_MAIN"]
    n_list = cfg["N_LIST"]
    snr_list = cfg["SNR_LIST"]
    expa = data["expa"]

    fig, axes = plt.subplots(1, len(methods), figsize=(4 * len(methods), 4.5), sharey=True)
    if len(methods) == 1:
        axes = [axes]

    for k, method in enumerate(methods):
        ax = axes[k]
        cov = np.full((len(snr_list), len(n_list)), np.nan)
        for i, snr in enumerate(snr_list):
            for j, n in enumerate(n_list):
                cell_key = f"{n}__{snr}"
                d = expa.get(cell_key, {}).get(method)
                if d:
                    cov[i, j] = d["cov_grid"][REF_IDX]

        im = ax.imshow(cov, aspect="auto", cmap="RdYlGn", vmin=0.5, vmax=1.0, origin="lower")
        ax.set_xticks(range(len(n_list)))
        ax.set_xticklabels([f"n={n}" for n in n_list])
        ax.set_yticks(range(len(snr_list)))
        ax.set_yticklabels([f"SNR={s}" for s in snr_list])
        ax.set_title(method, fontsize=11, fontweight="bold")
        for i in range(len(snr_list)):
            for j in range(len(n_list)):
                v = cov[i, j]
                if np.isfinite(v):
                    color = "white" if v < 0.7 else "black"
                    ax.text(j, i, f"{v:.3f}", ha="center", va="center",
                            color=color, fontsize=10, fontweight="bold")
        if k == len(methods) - 1:
            plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="Coverage (target=0.95)")

    fig.suptitle("F3 -- DGP2 coverage map: where does each method achieve nominal coverage?",
                  fontsize=12, fontweight="bold")
    fig.tight_layout()

    out = _FIGS_DIR / "phase16_F3_coverage_map.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# F4 -- bse vs dose curves (from EXP-A)
# ══════════════════════════════════════════════════════════════════════════════

def fig4_bse_vs_dose(data: dict):
    cfg = data["config"]
    methods = cfg["METHODS_MAIN"]
    n_list = cfg["N_LIST"]
    snr_list = cfg["SNR_LIST"]
    a_grid = np.array(cfg["A_GRID"])
    expa = data["expa"]

    fig, axes = plt.subplots(len(n_list), len(snr_list), figsize=(4 * len(snr_list), 3.5 * len(n_list)),
                              sharex=True, sharey="row")
    if len(n_list) == 1:
        axes = axes[None, :]
    if len(snr_list) == 1:
        axes = axes[:, None]

    for i, n in enumerate(n_list):
        for j, snr in enumerate(snr_list):
            ax = axes[i, j]
            cell_key = f"{n}__{snr}"
            cell = expa.get(cell_key, {})
            for method in methods:
                d = cell.get(method)
                if d is None:
                    continue
                bse = np.array(d["bse_grid"])
                ax.plot(a_grid, bse, marker="o",
                        label=METHOD_LABELS[method],
                        color=METHOD_COLORS.get(method, "grey"),
                        linewidth=2, markersize=6)
            ax.set_yscale("log")
            ax.axhline(0.1, color="grey", linestyle="--", alpha=0.5, linewidth=0.8)
            ax.set_title(f"n={n}, SNR={snr}", fontsize=10)
            if i == len(n_list) - 1:
                ax.set_xlabel("Dose a")
            if j == 0:
                ax.set_ylabel("|bias|/SE  (log scale)")
            ax.grid(True, alpha=0.3)

    # Single legend
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=len(methods),
                bbox_to_anchor=(0.5, 1.02), fontsize=10)

    fig.suptitle("F4 -- bse vs dose: REG > DR at boundary, DR best at centre",
                  fontsize=12, fontweight="bold", y=1.05)
    fig.tight_layout()

    out = _FIGS_DIR / "phase16_F4_bse_vs_dose.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# F5 -- Proxy feasibility 4-panel heatmap (from EXP-B)
# ══════════════════════════════════════════════════════════════════════════════

def fig5_proxy_feasibility(data: dict):
    cfg = data["config"]
    methods = cfg["METHODS_MAIN"]
    snr_levels = cfg["SNR_LEVELS_FEAS"]
    expb = data["expb"]

    n_methods = len(methods)
    rows = 2 if n_methods >= 3 else 1
    cols = (n_methods + rows - 1) // rows
    fig, axes = plt.subplots(rows, cols, figsize=(5 * cols, 4.5 * rows))
    if rows == 1 and cols == 1:
        axes = np.array([[axes]])
    elif rows == 1:
        axes = axes.reshape(1, -1)
    elif cols == 1:
        axes = axes.reshape(-1, 1)

    # Compute global vmin/vmax for shared colorbar
    all_bse = []
    for cell_key, cell in expb.items():
        for method in methods:
            d = cell.get(method)
            if d:
                v = d["bse_grid"][REF_IDX]
                if np.isfinite(v):
                    all_bse.append(v)
    if all_bse:
        vmin = max(np.percentile(all_bse, 5), 1e-3)
        vmax = np.percentile(all_bse, 95)
    else:
        vmin, vmax = 1e-3, 1.0

    from matplotlib.colors import LogNorm
    norm = LogNorm(vmin=vmin, vmax=vmax)

    for k, method in enumerate(methods):
        i, j = divmod(k, cols)
        ax = axes[i, j]
        bse_mat = np.full((len(snr_levels), len(snr_levels)), np.nan)
        for r, snr_W in enumerate(snr_levels):
            for c, snr_Z in enumerate(snr_levels):
                cell_key = f"{snr_W}__{snr_Z}"
                d = expb.get(cell_key, {}).get(method)
                if d:
                    bse_mat[r, c] = d["bse_grid"][REF_IDX]

        im = ax.imshow(bse_mat, aspect="auto", cmap="RdYlGn_r", norm=norm, origin="lower")
        ax.set_xticks(range(len(snr_levels)))
        ax.set_xticklabels([str(s) for s in snr_levels])
        ax.set_yticks(range(len(snr_levels)))
        ax.set_yticklabels([str(s) for s in snr_levels])
        ax.set_title(method, fontsize=11, fontweight="bold")
        ax.set_xlabel("SNR_Z")
        ax.set_ylabel("SNR_W")
        for r in range(len(snr_levels)):
            for c in range(len(snr_levels)):
                v = bse_mat[r, c]
                if np.isfinite(v):
                    txt = f"{v:.2g}" if v < 0.01 else f"{v:.3f}"
                    ax.text(c, r, txt, ha="center", va="center",
                            color="white" if v > 1.0 else "black", fontsize=8)
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="bse_ref (log scale)")

    # Hide unused axes
    for k in range(len(methods), rows * cols):
        i, j = divmod(k, cols)
        axes[i, j].axis("off")

    fig.suptitle("F5 -- Proxy feasibility: bse_ref by (SNR_W, SNR_Z) per method",
                  fontsize=12, fontweight="bold")
    fig.tight_layout()

    out = _FIGS_DIR / "phase16_F5_proxy_feasibility.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# F6 -- Spectral kappa vs bse scatter (from EXP-C)
# ══════════════════════════════════════════════════════════════════════════════

def fig6_spectral_correlation(data: dict):
    cfg = data["config"]
    methods = cfg["METHODS_MAIN"]
    expc = data["expc"]
    corrs = data["spectral_correlations"]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    for ax_idx, (diag_key, x_label) in enumerate([
        ("kappa_h_mean", "log10(kappa_h)"),
        ("kappa_r_mean", "log10(kappa_r)"),
    ]):
        ax = axes[ax_idx]
        for method in methods:
            xs, ys = [], []
            for cell_key, cell in expc.items():
                d = cell.get(method)
                if d is None:
                    continue
                x = d.get(diag_key, float("nan"))
                y = d["bse_grid"][REF_IDX]
                if np.isfinite(x) and np.isfinite(y) and x > 0:
                    xs.append(np.log10(x))
                    ys.append(y)
            if xs:
                rho_val = corrs.get(method, {}).get(diag_key, {}).get("rho", float("nan"))
                lab = f"{method} (rho={rho_val:.2f})" if np.isfinite(rho_val) else method
                ax.scatter(xs, ys, label=lab, color=METHOD_COLORS.get(method, "grey"),
                            s=80, alpha=0.85, edgecolors="black", linewidth=0.5)
        ax.set_xlabel(x_label, fontsize=11)
        ax.set_ylabel("bse_ref (observed)", fontsize=11)
        ax.set_yscale("log")
        ax.set_title(f"Spectral health: {diag_key.replace('_mean', '')}", fontsize=11, fontweight="bold")
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, loc="best")

    fig.suptitle("F6 -- Spectral diagnostics vs observed bse_ref (per method, across cells)",
                  fontsize=12, fontweight="bold")
    fig.tight_layout()

    out = _FIGS_DIR / "phase16_F6_spectral_correlation.png"
    fig.savefig(out, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out}")


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print("=== Phase 16 Figures ===\n")
    _FIGS_DIR.mkdir(parents=True, exist_ok=True)

    # F1 conceptual: no data needed
    print("[1/6] F1 conceptual...")
    fig1_bridge_mismatch()

    # F2 DGP1 sanity: from existing E1 pkls
    print("[2/6] F2 DGP1 sanity...")
    try:
        fig2_dgp1_sanity()
    except Exception as e:
        print(f"  ERROR: {e}")

    # Load synthesis data
    try:
        data = _load_data()
    except Exception as e:
        print(f"\n[STOP] Cannot generate F3-F6 without synthesis data: {e}")
        return

    print("[3/6] F3 coverage map...")
    fig3_coverage_map(data)

    print("[4/6] F4 bse vs dose...")
    fig4_bse_vs_dose(data)

    print("[5/6] F5 proxy feasibility...")
    fig5_proxy_feasibility(data)

    print("[6/6] F6 spectral correlation...")
    fig6_spectral_correlation(data)

    print(f"\n[DONE] All 6 figures in {_FIGS_DIR}")


if __name__ == "__main__":
    main()
